-- Generated by TalentDex Companion. Do not edit this file by hand.
local _, TalentDex = ...

TalentDex.generatedBuildData = {
    DEATHKNIGHT = {
        [251] = {
            ["Icy Veins"] = {
                ["Mythic+"] = { variantOrder = { "Frost Mythic+/Delves" }, variants = {
                    ["Frost Mythic+/Delves"] = { talentImportString = "CsPAAAAAAAAAAAAAAAAAAAAAAMDYmZMzMzYY2mZmZmZxMjMjxYYMGMzMzMzMzMDAAAAAAAAAjZbgBsAWGmAjFMzYmZgBghZGAgB" },
                } },
                ["PvP"] = { variantOrder = { "3v3", "Rider Frost Build" }, variants = {
                    ["3v3"] = { talentImportString = "CsPAAAAAAAAAAAAAAAAAAAAAAMDYmZYMzMDzyYmZYbGjmZMzMDzYYmZGMzMzMDAAAAAAAAAjZbgBsAWGmAjFjZGmZADghZGAGM" },
                    ["Rider Frost Build"] = { talentImportString = "CsPAAAAAAAAAAAAAAAAAAAAAAMDYmZYMzMDzyYmZYbGjmZMzMjZGYmZGMzMzMDAAAAAAAAAgNzmhBGY2YohNjZGmZADgBgZGGM" },
                } },
                ["Raid"] = { variantOrder = { "Frost Single Target" }, variants = {
                    ["Frost Single Target"] = { talentImportString = "CsPAAAAAAAAAAAAAAAAAAAAAAMDwMjZmZGDz2MzMzMLmZmMjxYYmxgZMzMzMzMDAAAAAAAAAgNzihBGY2YohNMzYmZgBgBgZGgB" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves (Best)" }, variants = {
                    ["Delves (Best)"] = { talentImportString = "CsPAAAAAAAAAAAAAAAAAAAAAAMAzMMzMDY2MzMzMLzMjMjxYYmxgZmZmZmZmZAAAAAAAAAYMbDMgFwywEyYBzMmZGYAYYmBYmBD" },
                } },
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "CsPAAAAAAAAAAAAAAAAAAAAAAMAzMMjZAz2MzMzMLzMjMjxYYmxgZmZmZmZmZAAAAAAAAAYMbDMgFwywEyYBzMmZGYAYYmBYmBD" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "CsPAAAAAAAAAAAAAAAAAAAAAAMAmZMjZAz2MzMzMLzMjMjxYYmxgZmZmZmZmZAAAAAAAAAYMbDMgFwywEyYBzMmZGYAYYmBYmBD" },
                } },
            },
        },
        [252] = {
            ["Icy Veins"] = {
                ["Mythic+"] = { variantOrder = { "Unholy Mythic+/Delves" }, variants = {
                    ["Unholy Mythic+/Delves"] = { talentImportString = "CwPAAAAAAAAAAAAAAAAAAAAAAAYmhZMzMDz2MzMTzmZGjZAAAAAAAAgZGzYAwyMmZ2MzYMjBGYGbassAYbwGGwMAMmZGzgZGMjxA" },
                } },
                ["PvP"] = { variantOrder = { "3v3", "Disease Build", "Pet Build" }, variants = {
                    ["3v3"] = { talentImportString = "CwPAAAAAAAAAAAAAAAAAAAAAAAYmBjZMDzyYmZa2mZGjhZAAAAAAAAMzwMDAWmxMjZmxMzA2MbGGYgZjhGLMAzAwYmZMDwMzYGD" },
                    ["Disease Build"] = { talentImportString = "CwPAAAAAAAAAAAAAAAAAAAAAAAYmBjZGjZWGzMTz2MGzMMDAAAAAAAgxwMDAWmZYMzMmZGwmZzwADMbM0YBAzAYmZmZMDwMzYGD" },
                    ["Pet Build"] = { talentImportString = "CwPAkXBWxkyfx9CbGaHonEAhLBYmBjZMDzyYmZa2mZGjhZAAAAAAAAMzwMDAWmxMjZmxMzA2MbGGyAzGDNWYAmBgxMzYGgZmxMG" },
                } },
                ["Raid"] = { variantOrder = { "Unholy Single-Target" }, variants = {
                    ["Unholy Single-Target"] = { talentImportString = "CwPAAAAAAAAAAAAAAAAAAAAAAAwMjZMzYY2mZmZa2MzMjZAAAAAAAAgZGGDAWmxMz2MzYmZAbmFDDMwsxQjFAMDAjZmxMAzMzYMA" },
                } },
            },
            ["Wowhead"] = {
                ["Mythic+"] = { variantOrder = { "M+/ Delves (Best)" }, variants = {
                    ["M+/ Delves (Best)"] = { talentImportString = "CwPAAAAAAAAAAAAAAAAAAAAAAAYmhZMGDz2MzMTzyMzYMjBAAAAAAAgZGDDAWmxMzmZGzMjBGYGbassAYbiNMgZAYMzMmBzMYMjB" },
                } },
                ["Raid"] = { variantOrder = { "Single Target (Best)" }, variants = {
                    ["Single Target (Best)"] = { talentImportString = "CwPAAAAAAAAAAAAAAAAAAAAAAAwMjZMDDz2MzMTzmZmZMjBAAAAAAAgZGmZAwyMmZ2mZGzMDYzsYYIDMbM0YBAzAAzMjZAmZmxYA" },
                } },
            },
        },
    },
    DEMONHUNTER = {
        [577] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Delves – Fel-Scarred" }, variants = {
                    ["Delves – Fel-Scarred"] = { talentImportString = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMjZMzMjxMhZGAAAAAAwsYmhZMzAzYZmZmxyMDmlB2mNzYY2YaMzMzM2AAAAAAAAYmBDAAAAD" },
                } },
                ["Mythic+"] = { variantOrder = { "AoE / Mythic+ – Fel-Scarred" }, variants = {
                    ["AoE / Mythic+ – Fel-Scarred"] = { talentImportString = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMz2MmZmxYmMmZAAAAAAAzixsNDzMwMWmZmZYmBzyAbzmZMMbMNmZGzYDAAAYAAAAMzgBAAAgB" },
                } },
                ["PvP"] = { variantOrder = { "3v3", "Felscarred Build" }, variants = {
                    ["3v3"] = { talentImportString = "CEkAAAAAAAAAAAAAAAAAAAAAAwgZmZMjxMjZmJDzAAAAAAAmFjZbMzMzsNzMWmZMjlZGmZbmlZwwYZjJMmZMjFAAAAAAAwMDwAAAAwA" },
                    ["Felscarred Build"] = { talentImportString = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZMzMjZMzMjZmJDDAAAAAAwsYMbzMmZmtZmBzYGmZYsNwysYGDzCTjZmxM2AAAAAAAAYmBDAAAAD" },
                } },
                ["Raid"] = { variantOrder = { "Fel-Scarred Raid Cleave Build", "Raid / Cleave – Fel-Scarred" }, variants = {
                    ["Fel-Scarred Raid Cleave Build"] = { talentImportString = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMjZMzMzMmJjZGAAAAAAwsZMbzMGDmZsMz8AzwMDmlB2mFzYY2YaMzMG2AAAAAAAAYmBDAAAAD" },
                    ["Raid / Cleave – Fel-Scarred"] = { talentImportString = "CEkAAAAAAAAAAAAAAAAAAAAAAYgZmZMjZmZmxMZMzAAAAAAAmNjZbmxYmtZmxyMjZsMzwMLzsMDGGLbMhxMjhFAAAAAAAwMDwAAAAwA" },
                } },
            },
            ["Wowhead"] = {
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMz2MmZmxYmMmZAAAAAAAzixsNDzMwMWmZmZYmBzyALzmZMMLaaMzMmxGAAAwAAAAYmBDAAAAD" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "CEkAAAAAAAAAAAAAAAAAAAAAAYmZGzMzmxMzMmZmMmZAAAAAAAzyDMmtZYmBzMWmZMDzMGzyALziZMMbaaMzMG2AAAAAAAAYmBDAAAAD" },
                } },
            },
        },
    },
    DRUID = {
        [102] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Balance Druid Delves - Keeper" }, variants = {
                    ["Balance Druid Delves - Keeper"] = { talentImportString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMD8AmlZmZmZDgZZmtZWmxMzGLzYMGzshBADw22YBTzMbDAAAA2MzMzMYzYGjBgZGAYA" },
                } },
                ["PvP"] = { variantOrder = { "3v3", "Blitz" }, variants = {
                    ["3v3"] = { talentImportString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMLNjxMDwsZmZmZjxwMLjlZMjZGjlZMzMD2wAgBYbbshpZmlBAAAAbmZmZGsZYMGAmZAgBA" },
                    ["Blitz"] = { talentImportString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMLNjxMDwsZmZmZhxgZZsMjZmZGjlZWmZmBbYAwAstN2w0MzyAAAAgNzMzMD2MMGDAzMAwA" },
                } },
                ["Raid"] = { variantOrder = { "Balance Druid Single-Target - Elune's" }, variants = {
                    ["Balance Druid Single-Target - Elune's"] = { talentImportString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMD8AmFzMzMLMMMmZZGGzYhlZWmZMmZDDAGbLzMYMbDgJAAAALMzMzgNjZMmBAwMDWGA" },
                } },
            },
            ["Wowhead"] = {
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNMmZgxsMzMzMLMgxMLzsYmZswyMLjxMjNMAYstNzgxsNCMBAAAYhZmZGsZMjxAAwMDWGA" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "CYGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWoMbNjxMDwsMzMzMYYGjZWmhxMWYZmlZGjZ2wAgx2yMDGz2IwEAAAgFzMzMD2MMGzAAYmBLDA" },
                } },
            },
        },
        [103] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Delves - Druid of the Claw" }, variants = {
                    ["Delves - Druid of the Claw"] = { talentImportString = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZYmxMzMzsZsNz2MmZegZGAAAA2CmNDPgZG1MmlxMzMLjZYAAAAAAMwAAAAoZWmlZmZAALwMzAswgBAAwMbYA" },
                } },
                ["Mythic+"] = { variantOrder = { "AoE / Mythic+ - Druid of the Claw" }, variants = {
                    ["AoE / Mythic+ - Druid of the Claw"] = { talentImportString = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZ2YmZmxY2MPw2YbGzMmZAAAAYLY2M8AmZUzYWMzMzsMmxAAAAAAwADAAAgmZZWmZmBAsAzMDwCDGAAAzshB" },
                } },
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Feral Druid in	Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Feral Druid in	Arena"] = { talentImportString = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZWYmZmZGz2CLzsMjZMzMAAAAsEMbGYmZqZMbmZmZWGz8AGAAAAAAgBAAAAAY2mZpZbmlNYmZAWYwAAYmBAD" },
                } },
                ["Raid"] = { variantOrder = { "Raid / Cleave - Wildstalker", "Raid / Single Target - Wildstalker" }, variants = {
                    ["Raid / Cleave - Wildstalker"] = { talentImportString = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZMzGzMzMGz2yYZsNjZmHYmBAAAgtgZzwYmRNjZZmZmZMmxAAAAAAwADAAAAAwsNzSzyMLbgZeAgFzgBAwMDAGA" },
                    ["Raid / Single Target - Wildstalker"] = { talentImportString = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAwYMjxYmZMmtFWGbzMzYmZAAAAYLY2MMmZUzYWmZmZGjZMAAAAAAMwAAAAAAMbzs0sNzyGYmHAYxMYAAMzAgB" },
                } },
            },
            ["Wowhead"] = {
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZ2YmZmxY2MPw2YbGzMmZAAAAYJY2gxMjaGzCzMzsMmZGAAAAAAADAAAgAgZbmlmlZW2AzMALMDDAgZGAMA" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "CcGAAAAAAAAAAAAAAAAAAAAAAAAAAAAwghxYmZmxsxDsMz2MzMmZGAAAAWCmNYMzomxswMzMGzMDAAAAAAgBAAAQzsMLzMzACsAmZAWMzwAAAYmNMA" },
                } },
            },
        },
        [105] = {
            ["Icy Veins"] = {
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Restoration Druid in Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Restoration Druid in Arena"] = { talentImportString = "CkGAAAAAAAAAAAAAAAAAAAAAAMMmZhZMzMmlxMjxsxsYbAAAAAAAAAAglZIMjpZmZgZzMzMziBzAAAAAYAAjBstNWw0MzyAAAAYhxMzwM2ANDAmZAADA" },
                } },
            },
        },
    },
    EVOKER = {
        [1467] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Scalecommander Raid/Delves -" }, variants = {
                    ["Scalecommander Raid/Delves -"] = { talentImportString = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZgZYGzMgBjZamZmpZmx2MMzMzMzMzAmxMGzMLzMDMwYwGsMGN2GAzAwGGYmBDD" },
                } },
                ["Mythic+"] = { variantOrder = { "Scalecommander Mythic+ -" }, variants = {
                    ["Scalecommander Mythic+ -"] = { talentImportString = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZAMzwMwMYMTjZmpZmZ2mhZmZmZmZGwMzMGzMLzMDMwYwGsMGN2GAzAwGGYmBDD" },
                } },
                ["PvP"] = { variantOrder = { "3v3" }, variants = {
                    ["3v3"] = { talentImportString = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgZmZGMDzwMMzwYMTjZmpZwyMMzMzMzMzAMjZYmZZMDMwYwGsMGN2GAzAwGGYmBGD" },
                } },
                ["Raid"] = { variantOrder = { "Scalecommander Single-Target Raid Build" }, variants = {
                    ["Scalecommander Single-Target Raid Build"] = { talentImportString = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzMDMDzwMgBjZaMzMNjx2wMzMzMzMzAmZmxYmZZmZgBGD2glxox2AYGA2wMYmBDD" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves (Best)" }, variants = {
                    ["Delves (Best)"] = { talentImportString = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwMjZgZYmhBGGjZaMzMNjxyMmZmZmZmZGwMzYYmZZmZgBYwGsMGN2GQmBBbYgZGMjB" },
                } },
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZwgZGmBGYMTjZmpZmZ2mZmZmZmZmZGwMzMzYmZZmZgBGD2glxox2AyMIYDzgZGM8AA" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "CsbBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjZwMDzwMgBjZaMzMNzM2mZmZmZmZmZGwMmZGzMLzMDMwYwGsMGN2GQmBBbYgZGMjHA" },
                } },
            },
        },
        [1468] = {
            ["Icy Veins"] = {
                ["PvP"] = { variantOrder = { "3v3" }, variants = {
                    ["3v3"] = { talentImportString = "CwbBAAAAAAAAAAAAAAAAAAAAAAAAAAAegZmZ22GYYmZYmxYsNMAAwMMzMzYYmwMDAAAsNzMTzYMzMLjZAAYMjNWgBmhhGwCMmZAYA" },
                } },
            },
        },
        [1473] = {
            ["Icy Veins"] = {
                ["Mythic+"] = { variantOrder = { "High Key Mythic+ Build - Chronowarden", "Weekly Mythic+ Build - Scalecommander" }, variants = {
                    ["High Key Mythic+ Build - Chronowarden"] = { talentImportString = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbzMzgZYmZZGzMjZ2AAAAAAAAYmhZGYM1YmZGAAAAMjZMmZWGzMwMMwYGLsADMDDNwCGzMzAAD" },
                    ["Weekly Mythic+ Build - Scalecommander"] = { talentImportString = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbjZmxyMYmtZMzMmBAAAAAAAAmhHYGYM1YmZGAAAAMzMjxMz2YmBmZzYwCsMGGbDgZQshxMYmBDG" },
                } },
                ["PvP"] = { variantOrder = { "3v3" }, variants = {
                    ["3v3"] = { talentImportString = "CEcBAAAAAAAAAAAAAAAAAAAAAgZGbzMzM2mxMzsNMzMmZDAAAAADAAYGmZYMUzMzMDAAAAmZmBzMbjZAmFjBbwyYYsNAmBxGGDMzADD" },
                } },
                ["Raid"] = { variantOrder = { "Raiding Build - Chronowarden" }, variants = {
                    ["Raiding Build - Chronowarden"] = { talentImportString = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbzMzgZYmZZGzMjZ2AAAAAAAAYmhxMYM1YmZGAAAAMjZMmZWGzMwMMwYGLsADMDDNwCGjZGAYA" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves (Best)" }, variants = {
                    ["Delves (Best)"] = { talentImportString = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbjZmxyMYmlZMzMmBAAAAAAAAmhZGYM1YmZGAAAAMzMjxMzyYmBmZzYwCsMGGbDgZiYDjZwMDgB" },
                } },
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbjZGMDzMLzYmZMzGAAAAAAAAmhZGYM1YmZGAAAAMzMjxMz2YmBmZzYwCsMGGbDgZiYDjZwMDgB" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "CEcBAAAAAAAAAAAAAAAAAAAAAMMzMbzMzgZYmZZGzMjZ2AAAAAAAAYmhxMYM1YmZGAAAAMjZMmZWGzMwMMwYGLsADMDDNiFMGzMAwA" },
                } },
            },
        },
    },
    HUNTER = {
        [253] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Beast Mastery Delves - Pack Leader" }, variants = {
                    ["Beast Mastery Delves - Pack Leader"] = { talentImportString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGzMzs8AzYmZmZMzgZGzMMzYmZGMGzYmhx0AAAAAAAAAzMGDYmNCWmZBsNAA" },
                } },
                ["Mythic+"] = { variantOrder = { "Beast Mastery Mythic+ - Pack Leader" }, variants = {
                    ["Beast Mastery Mythic+ - Pack Leader"] = { talentImportString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGzMzs8AzYmZmZMzgZGzMMzYmZGbzMjZMDLjpZAAAAAAAAgHYMGwMbEwsA2GAA" },
                } },
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Beast Mastery Hunters" }, variants = {
                    ["Midnight PvP Talent Builds for Beast Mastery Hunters"] = { talentImportString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGzYmFzwMmZY8AzMGmxMzwYGLmZMzMjhRzAAAAAmBAAgZGzMgZ2gFMzCYZAYA" },
                } },
                ["Raid"] = { variantOrder = { "Beast Mastery Raid AoE/Cleave - Pack Leader", "Beast Mastery Single-Target - Pack Leader" }, variants = {
                    ["Beast Mastery Raid AoE/Cleave - Pack Leader"] = { talentImportString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGmZmlZGzMzMjZGMzYmhZGzYmFzMjZMDGTzAAAAAAAAgxMzAMzGZDmFw2AwA" },
                    ["Beast Mastery Single-Target - Pack Leader"] = { talentImportString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwwMsBAgZYMzyMDzYmhhZGjZGzMjZMziZmxMmBjpZAAAAAzAAAwYmZAmZjxGMLgtBgB" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves (Best)" }, variants = {
                    ["Delves (Best)"] = { talentImportString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGPwMzsMzwMzMjZGMzYmhZmZGzwMzwYmhx0MAAAAAAAAYMmBYmNCWmZBsNAM" },
                } },
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsBzwQDbAAYGPwMzsMzwMzMjZGMzYmhZGzMzYbmZYMDLDNDAAAAAAAAmHYMzAmZjAmFw2AwA" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "C0PAAAAAAAAAAAAAAAAAAAAAAAMmxwCsAzwQDbAAYGGzsMzwMmZYYmxYmxMzYGzwMzYGzghmBAAAAMDAAAzMzMAzsRYYWAbDAD" },
                } },
            },
        },
        [254] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Marksmanship Delves - Sentinel" }, variants = {
                    ["Marksmanship Delves - Sentinel"] = { talentImportString = "C4PAAAAAAAAAAAAAAAAAAAAAAwGMwMGzYZAjZwGAAAAAAAAYGzMzgxMzYmhx0wgZZbbmZmZmZmZWwsNMDAAwMjxAwM2wyMAbMz2MG" },
                } },
                ["Mythic+"] = { variantOrder = { "Marksmanship Mythic+ - Sentinel" }, variants = {
                    ["Marksmanship Mythic+ - Sentinel"] = { talentImportString = "C4PAAAAAAAAAAAAAAAAAAAAAAwGMwMGzYZAjZwGAAAAAAAAYGzMzYbGzMjZYZMNjBzy22MzMzMzMzswMLDzAAA4BGjBgZsBGgNmZbGD" },
                } },
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Marksmanship Hunters in Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Marksmanship Hunters in Arena"] = { talentImportString = "C4PAAAAAAAAAAAAAAAAAAAAAAYzsMwAGwMsFYWAAAAAAAAAzwYGLGzMzMjhRzYmxsZbGjZmZG2GzsMYAAAmZMzMzMDILYGgFmZZGD" },
                } },
                ["Raid"] = { variantOrder = { "Marksmanship Raid AoE/Cleave - Sentinel", "Marksmanship Single Target - Sentinel" }, variants = {
                    ["Marksmanship Raid AoE/Cleave - Sentinel"] = { talentImportString = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAjZwGAAAAAAAAYGzYmFzYmZMDGTzYwstZmZmZmZmZWYmlhZAAAGzMjBwM22gBYjZ2mxAA" },
                    ["Marksmanship Single Target - Sentinel"] = { talentImportString = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAjZwGAAAAAAAAYGzYmFzYmZMDGTzYwYbZmZmZmZmZWYmlBzAAAGzMjBwM22gBYjZ2mxAA" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves (Best)" }, variants = {
                    ["Delves (Best)"] = { talentImportString = "C4PAAAAAAAAAAAAAAAAAAAAAAwGMwMGzYZAMD2AAAAAAAAAzYmZGMmZGzMMmGGMLbLzMzMzMzMzCmthZAAAmZMGAmpNsMDwGzsNjB" },
                } },
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "C4PAAAAAAAAAAAAAAAAAAAAAAwGMwMGzYZAMD2AAAAAAAAAzYmZGbzYmZMDLjpZMYW22mZmZmZmZmFmZZYGAAAPwYMAMTbgBYjZ2mxA" },
                } },
                ["Raid"] = { variantOrder = { "Raid AoE/ Cleave (Best)", "Single Target (Best)" }, variants = {
                    ["Raid AoE/ Cleave (Best)"] = { talentImportString = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAMD2AAAAAAAAAzYmZmFzYmZMDGTzYwstZmZmZmZmZWwsMMDAAwYmZMAmptNYA2YmtZMA" },
                    ["Single Target (Best)"] = { talentImportString = "C4PAAAAAAAAAAAAAAAAAAAAAAwCMwMGzYZAMD2AAAAAAAAAzYmZmFzYmZMDGTzYwYbZmZmZmZmZWwsMYGAAwYmZMAmptNYA2YmtZMA" },
                } },
            },
        },
        [255] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Survival Delves - Sentinel" }, variants = {
                    ["Survival Delves - Sentinel"] = { talentImportString = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxYGLDgZGYbmZmZmxsNPAAAAAAgZMzMDGjZMzwYaAAAAAAGLLzMWwMzMzYMAMjNsMjxMzmBAAA" },
                } },
                ["Mythic+"] = { variantOrder = { "Survival Mythic+ - Sentinel" }, variants = {
                    ["Survival Mythic+ - Sentinel"] = { talentImportString = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxYGLDgZGYbmZmZmxsNPAAAAAAgZMzMjtZMmxMsMmmBAAAYAgxyyMjFMzMegxYAYGbgxYmZzAAA" },
                } },
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Survival Hunters in Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Survival Hunters in Arena"] = { talentImportString = "C8PAAAAAAAAAAAAAAAAAAAAAAMgxMG2gNYGGawyMmZGjZbAAAAAAYGGzssMjxMMGzIDAAAwAAssMzMLmZmxMjZGwMLwCmxYmZxAA" },
                } },
                ["Raid"] = { variantOrder = { "Survival Single Target - Sentinel" }, variants = {
                    ["Survival Single Target - Sentinel"] = { talentImportString = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxoxyAYmgtZMzMGzyAAAAAAwMmxMLmxYGzgx0MAAAADAmxyyMzsYMzMjZmBAzYZDGDjNDAA" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves (Best)" }, variants = {
                    ["Delves (Best)"] = { talentImportString = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxoxyAYmgtZmZmZmZ2mBAAAAAwMzMzMMjhxMDjpZAAAAGAgltZGLDzMGjxAwM2gZMMziBA" },
                } },
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)", "Mythic+ Pre Tier-set (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxoxyAYmgtZmZmxMz2MAAAAAAmxMzMMjxMmBjpZAAAAGAgltZGLzYmxYMzAwM2wixwMLGAA" },
                    ["Mythic+ Pre Tier-set (Best)"] = { talentImportString = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxoxyAYmgtZmZmxMz2MAAAAAAmxMzMMjxMmBjpZAAAAGAgltZGbzYmxYMzAwM2wixwMLGAA" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "C8PAAAAAAAAAAAAAAAAAAAAAAMWgBmxoxyAYmgNjZmxwyAAAAAAwMmZmhZMmxMYMNDAAAwAgZstMzMLmZmZGzMzAwMWAjxMWMAA" },
                } },
            },
        },
    },
    MAGE = {
        [62] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Arcane Delves - Sunfury" }, variants = {
                    ["Arcane Delves - Sunfury"] = { talentImportString = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZGzsYzMDNzYGAAADAYmZaWWWmBAwGAAbwMzwmlZMzyMGzMzMDbMjZMDAwAAAMAzMwMDAGmZG" },
                } },
                ["Mythic+"] = { variantOrder = { "Arcane Mythic+ - Sunfury" }, variants = {
                    ["Arcane Mythic+ - Sunfury"] = { talentImportString = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzQzMzAAAwAAmZmmlllZAAsBAwGMzMsZZGzsMjxMzMzwGzYGzAAMAAADwMDMzAghZmB" },
                } },
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Arcane Mage in Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Arcane Mage in Arena"] = { talentImportString = "C4DAAAAAAAAAAAAAAAAAAAAAAMmtlZWmZmZzmZGaGmBAAwAAAAzMzssNzELAAsMMzMGLWmZmxMzYMzMzYhZMjZAAGAAAzsAAjBADDD" },
                } },
                ["Raid"] = { variantOrder = { "Sunfury Pure Single-Target Build", "Arcane Raid - Sunfury" }, variants = {
                    ["Sunfury Pure Single-Target Build"] = { talentImportString = "C4DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDamZGAAAGAwMz0sssMDAgNAAgZmZGbWmZmZZGjxMzgNmxMzMAADAAwAMzAmBADzMD" },
                    ["Arcane Raid - Sunfury"] = { talentImportString = "C4DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDamZGAAAGAwMz0sssMDAgNAAAzMDbWmxMLzYMzMzMsxMmZmBAYAAAGgZGwMAYYmZA" },
                } },
            },
            ["Wowhead"] = {
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "C4DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzQzMGAAAGAwMz0sssMDAEbAAsBzMDbWmxMLzYMzMzMswMzMzMAADAAwAMzAMAYYmZA" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "C4DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDamZGAAAGAwMz0sssMDAEbAAAmZG2sMjZWmxYmZmZYhZMzMDAwAAAMAzMgZAwwMzA" },
                } },
            },
        },
        [63] = {
            ["Icy Veins"] = {
                ["Mythic+"] = { variantOrder = { "Fire Mythic+ - Sunfury" }, variants = {
                    ["Fire Mythic+ - Sunfury"] = { talentImportString = "C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsgZGZmZGAAAAAmZmmltlZAA2MzM2mZmZGbAAAAAYzMjZGAAMjxMzMjZmlBgZGMjxAmhxA" },
                } },
                ["PvP"] = { variantOrder = { "3v3" }, variants = {
                    ["3v3"] = { talentImportString = "C8DAAAAAAAAAAAAAAAAAAAAAAMstMzyMzMb2MzIzwMAAAmZZGzMLzCAAAYxMjZbMzMjFAAAAAsYmZmBAAGmZmhxMzyMwMDIjBGmhBA" },
                } },
                ["Raid"] = { variantOrder = { "Fire Raid - Sunfury" }, variants = {
                    ["Fire Raid - Sunfury"] = { talentImportString = "C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMDZmZGAAAGAwMz0sstMDAwmZmx2MzMzYDAAAAAbmZMzAAgZMmZmZMzsMAMzAMGwMMGA" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves (Best)" }, variants = {
                    ["Delves (Best)"] = { talentImportString = "C8DAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzIzMzAAAwMLzYmZZWgAAAWMzM2mZmZmZDAAAAALmZmZAAgZMmZmZMzsAMzAyYMgBjB" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "C8DAAAAAAAAAAAAAAAAAAAAAAYGGLzMzswMzIzMzAAAwAAmZmmlttZAA2MzM2mZmZGLAAAAAYxMjZAAgZMmZmZMzsMAMzQGjBMDjB" },
                } },
            },
        },
        [64] = {
            ["Icy Veins"] = {
                ["PvP"] = { variantOrder = { "3v3" }, variants = {
                    ["3v3"] = { talentImportString = "CAEAAAAAAAAAAAAAAAAAAAAAAMmtlZWmZmZDzMxMMzMzMzsYmZGzYGAAAYmZmllZm2AAgFAAAwGAbLjZmBsMPgxMjFAAAmZBYGGzAGMA" },
                } },
                ["Raid"] = { variantOrder = { "Frost Light Cleave/Raid", "Frost Single Target" }, variants = {
                    ["Frost Light Cleave/Raid"] = { talentImportString = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGzMzMziZmZMjZAAAgZmZWWmZaDAAAAAA2AYbbMzMDmthxMsAAAwMbAzADYGMMA" },
                    ["Frost Single Target"] = { talentImportString = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGjZMziZmZmZMDAAAMzMzyyMTbAAAAAAwGAbbjZmZwsNPgxMsAAAwMbAzADYGMMA" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves (Best)" }, variants = {
                    ["Delves (Best)"] = { talentImportString = "CAEAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzEzMmZmZmZWMzMjZMDAAAMzMzyyMTbAAwCAAAYBgtlxMzMY2GGzwCAAAzsBMTGDYGMMA" },
                } },
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "CAEAAAAAAAAAAAAAAAAAAAAAAMzwYZmZmFMzEzMmZmZmZWMzMzMzMzsMTzMbzCAAAaBAAWAAAAAYbZMzMDmtZMzM2WAAAAzMYmMGwAYA" },
                } },
                ["Raid"] = { variantOrder = { "Raid Cleave (Best Spread Cleave)", "Raid Cleave (Best Stacked Cleave)", "Raid ST (Best ST)" }, variants = {
                    ["Raid Cleave (Best Spread Cleave)"] = { talentImportString = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGzMzMziZmZMjZAAAgZmZWWmZaDAAAAAA2AYbZMzMDmthxMsAAAwMbAzEGwMYYA" },
                    ["Raid Cleave (Best Stacked Cleave)"] = { talentImportString = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmxYmZmZWMzMzMzMzsMTzMbzCAAAaBAAAAAAAw2yYmZGMbzYmZstAAAAmZwMZMgBwA" },
                    ["Raid ST (Best ST)"] = { talentImportString = "CAEAAAAAAAAAAAAAAAAAAAAAAYGGLzMzsMmZmYmZGjZMziZmZmZMDAAAMzMzyyMTbAAAAAAwGAbLjZmZgtZMzMsAAAwMbAzEGwADD" },
                } },
            },
        },
    },
    MONK = {
        [269] = {
            ["Icy Veins"] = {
                ["Mythic+"] = { variantOrder = { "Windwalker Mythic+ - Conduit of the Celestials" }, variants = {
                    ["Windwalker Mythic+ - Conduit of the Celestials"] = { talentImportString = "C0QAAAAAAAAAAAAAAAAAAAAAAMzYMgxYZmZ2mBAAAAAAAAAAAYZYEmhhBMjhZmZGmNMDzyMBAswsxMmZmZAAsYmlZZMBAAmZGAzAMWGDYmZ2M" },
                } },
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Windwalker Monk in Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Windwalker Monk in Arena"] = { talentImportString = "C0QAAAAAAAAAAAAAAAAAAAAAAMzMjBjBbzMz2MAAAAAAAAAAAALDjwMzGGwwMmZmZY2mFGmlZCAYzMLjhxMzAAYDAmtZpZmZWAGGYmBAWGDYAD" },
                } },
                ["Raid"] = { variantOrder = { "Windwalker Raids - Shado-Pan" }, variants = {
                    ["Windwalker Raids - Shado-Pan"] = { talentImportString = "C0QAAAAAAAAAAAAAAAAAAAAAAMzYM2GmhlZGbzAAAAAAAAAAAAsMMCzwwAmZGmZmZY2GmhZZmAAWMz2MjZmZmBAwGAMLzSzMzsAgBmZAYsMAGwFA" },
                } },
            },
        },
        [270] = {
            ["Icy Veins"] = {
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Mistweaver Monk in Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Mistweaver Monk in Arena"] = { talentImportString = "C4QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgxMzyYZMbWMmZwYZbZGsZmtltZGbMjmxMgBzihZbmZmhZbWAz2MBAAAAmlptZbmlZDAAAgBjZmBAAADA" },
                } },
            },
        },
    },
    PALADIN = {
        [65] = {
            ["Icy Veins"] = {
                ["PvP"] = { variantOrder = { "3v3" }, variants = {
                    ["3v3"] = { talentImportString = "CEEAAAAAAAAAAAAAAAAAAAAAAAAAALAwMAADWGGMzyMzsMDjZsN2mZWMTTMLzwMDDbZAYAYDsZ2MzAAAAzMLbLWmZYjNGGbmhZGGMAmZAwAaA" },
                } },
            },
        },
        [70] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Retribution Delves - Templar" }, variants = {
                    ["Retribution Delves - Templar"] = { talentImportString = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAwoZbbmZWGjZmBAAAAAYmyYGMjtZmthZ2mxYMzwM2YDAAgZm2mZ2mBAsBYAAzwAzYGbYZGMmxMGMA" },
                } },
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Retribution Paladins in Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Retribution Paladins in Arena"] = { talentImportString = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAgBAoZZbmZWGmZMAAAAAAzUmlZYmx2w2wMbzYMmZYGLsNAMLzyMzs1AAAALAGAjxMmBmxwGwMzwYYwA" },
                } },
                ["Raid"] = { variantOrder = { "Retribution Single Target - Herald of the Sun" }, variants = {
                    ["Retribution Single Target - Herald of the Sun"] = { talentImportString = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAANbbzMzywMDAAAAAAzUGzwMjtxsNMz2MGjxwMWYbAYWmtZmZrBBAAsAYAwYGmBzYmZDYmZYMjBD" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves (Best)" }, variants = {
                    ["Delves (Best)"] = { talentImportString = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAwoZbbmZWGjZmBAAAAAYmyYGMjtZmthZ2mxYMzwM2YDAAIzMtNzsNDAYDwAAmhBmxM2wyMYMjZMYA" },
                } },
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAwoZbbmZWGzMzAAAAAAYmyYGmZsNmthZ2mxYMGmxCbAYWmtZmZrBBAAsAYAwYGGYGzMbAzMDjZMYA" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "CYEAAAAAAAAAAAAAAAAAAAAAAAAAAAANbbzMzywMDAAAAAAzUGzwMjtxsNMz2MGjxwMWYbAYWmtZmZrBBAAsAYAwYGmBzYmZDYmZYMjBD" },
                } },
            },
        },
    },
    PRIEST = {
        [256] = {
            ["Icy Veins"] = {
                ["PvP"] = { variantOrder = { "Best Midnight PvP Talent Builds for Discipline Priest" }, variants = {
                    ["Best Midnight PvP Talent Builds for Discipline Priest"] = { talentImportString = "CAQAAAAAAAAAAAAAAAAAAAAAAADsMzwyMjZmBMbzYmZGjZGAAAAAAAAAAzMzyMYMGLmZmhlFTzEDwMbYIMmtBYMYBAAGzwYYGAzMzAG" },
                } },
            },
        },
        [257] = {
            ["Icy Veins"] = {
                ["PvP"] = { variantOrder = { "3v3" }, variants = {
                    ["3v3"] = { talentImportString = "CEQAAAAAAAAAAAAAAAAAAAAAAwYAAAAAAAmZmxsMzMmZGDzgZbmZmBAAAwYmFYmZMWmZGDLLGzUAMzGGCjZbAGDswMAwMmxMGMAmZmB+AA" },
                } },
            },
        },
        [258] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Shadow Delves - Voidweaver" }, variants = {
                    ["Shadow Delves - Voidweaver"] = { talentImportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMzyMzYmx2MYmZmZDZGLb0AMzMDAEgZb2WAzGDAMwMzMzMbMDmZwMYA" },
                } },
                ["Mythic+"] = { variantOrder = { "Archon Raid - Ulatek (Mythic)" }, variants = {
                    ["Archon Raid - Ulatek (Mythic)"] = { talentImportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDPAAAAAAAAAAAAghZxMmZZmxMz2MGzw2MzYmZGbIzYxMNAzAMziZY2MAkxYBAzMGZMzMjZjZ2WGgZiB" },
                } },
                ["PvP"] = { variantOrder = { "3v3" }, variants = {
                    ["3v3"] = { talentImportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMDjBAAAAAAAAAAAADLzMGLzMmZ2mZYMz2YGzMzYZMZYZx0AMzMDAEgZb2WAzGDwYmBjZGjZZmBmZwMYA" },
                } },
                ["Raid"] = { variantOrder = { "Archon Raid - Entombed Sentinels", "Archon Raid - Lost Explorers", "Archon Raid - No 4pc Season 2", "Archon Raid - Sszorak", "Archon Raid - Ulatek (Heroic)", "Shadow Raid - Archon", "Voidweaver Raid - Entombed Sentinels", "Voidweaver Raid - Lost Explorers", "Voidweaver Raid - No 4pc Season 2", "Voidweaver Raid - Sszorak" }, variants = {
                    ["Archon Raid - Entombed Sentinels"] = { talentImportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDzAAAAAAAAAAAAMmZxMGbzMmZ2mBzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA" },
                    ["Archon Raid - Lost Explorers"] = { talentImportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDPAAAAAAAAAAAAghZxMmZbmxMz2MGzw2MzYmZGbIzYxMNAzAMzmZ0sZAIjxCAmZMYMzMjZjZ2WGgZwA" },
                    ["Archon Raid - No 4pc Season 2"] = { talentImportString = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMjtZMmZmBmMwMNzAzAMzmZ0sZAIjxCAmBYMzMjZbMz2yAMDGA" },
                    ["Archon Raid - Sszorak"] = { talentImportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDzAAAAAAAAAAAAwMLmxMbzMGz2MGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA" },
                    ["Archon Raid - Ulatek (Heroic)"] = { talentImportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZZmxMz2MGzw2MzYmZGbIzYxMNAzAMziZY2MAkxYBAzMIjZmZMbMz2yAMTMA" },
                    ["Shadow Raid - Archon"] = { talentImportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMDDAAAAAAAAAAAAmZxMmZbmxMz2MGzw2MzYmZGbIzYxMNAzAMzmZY2MAkxYBAzMgxMzMmNmZbZAmBDA" },
                    ["Voidweaver Raid - Entombed Sentinels"] = { talentImportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAgxDMLmxYbmhZ2mZYG2mZGzMzYDZGLmpBYmZGAIAz2stAmNGAYwYmZGz2YGMzgZwA" },
                    ["Voidweaver Raid - Lost Explorers"] = { talentImportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMjZMAAAAAAAAAAAAYMLzMGbzMmZ2mZGzw2MzYmZGbIzYxMNAzMzAABY2mtFwsxAADGzMzY2GzgZGMDGA" },
                    ["Voidweaver Raid - No 4pc Season 2"] = { talentImportString = "CIQAR03Gt7xPmcDNOjs2Zlb3yOMjZGAAAAAAAAAAAgxMMjx2MDzsNzwMsNzMmZmxGyMWMTDwMzMAQAmtZbJY2YAmBYMzMjZbMDmZwMYA" },
                    ["Voidweaver Raid - Sszorak"] = { talentImportString = "CIQAAAAAAAAAAAAAAAAAAAAAAMMjZGAAAAAAAAAAAAegZxMmZbmBz2MzYG2mZGzMzYDZGLmpBYmZGAIAz2stAmNGAYwYmZGz2YGMzgZwA" },
                } },
            },
        },
    },
    ROGUE = {
        [259] = {
            ["Icy Veins"] = {
                ["Mythic+"] = { variantOrder = { "Assassination Mythic+/Delves - Fatebound" }, variants = {
                    ["Assassination Mythic+/Delves - Fatebound"] = { talentImportString = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlZmFDAAAAAAzygtZAAAAAAttNzMzMzMGLzMzsNzyMz8AmxMjxwMjxAYgFYGjGzCgtBsZAwMzMMA" },
                } },
                ["PvP"] = { variantOrder = { "Best Midnight PvP Talent Builds for Assassination Rogue in Arena" }, variants = {
                    ["Best Midnight PvP Talent Builds for Assassination Rogue in Arena"] = { talentImportString = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsZGAAAAAAz2MmtZAAAAAAtsMMYmxYbmZmtZWmZGzMzMDmxMmZGGYgFYGjGzCgtBsNDbAzMDGA" },
                } },
                ["Raid"] = { variantOrder = { "Assassination Pure Single-Target - Fatebound", "Assassination Raid Cleave - Fatebound" }, variants = {
                    ["Assassination Pure Single-Target - Fatebound"] = { talentImportString = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsNDGAAAAAY2GsNDAAAAAIbzMzMzMjxyMzMbzsMzMzYGzYMmZMMAGYBmxoxsBYbAbGAMzMGD" },
                    ["Assassination Raid Cleave - Fatebound"] = { talentImportString = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsZwAAAAAAzygtZAAAAAAttNzMzMzMGLzMzsNzyMz8AjxMjxYmZmxAYgFYGjGzGgtBsZAwMzgB" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves (Best)" }, variants = {
                    ["Delves (Best)"] = { talentImportString = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlZmFDAAAAAAzygtZAAAAAAttNzMzMzMGLzMzsNzyMz8AmxMjxMmZMGgNzyADYJYZYCMsYwMDgZ8BA" },
                } },
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlZmFDAAAAAAzygtZAAAAAAttNzMzMzMGLzMzsNzyMz8AmxMjxMmZMGADsAzY0YWAZbAbGAMzMDfA" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)", "Raid Single Target (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsZwAAAAAAzygtZAAAAAAttNzMzMzMGLzMzsNzyMz8AjxMjxYmZmxAYgFYGjGzGIbDYzAgZmBD" },
                    ["Raid Single Target (Best)"] = { talentImportString = "CMQAAAAAAAAAAAAAAAAAAAAAAYmlxsNDGAAAAAYWGsNDAAAAAottZmZmZmxYZmZmtZWmZmZMjZMGzMGGADsAzY0Y2AZbAbGAMzMYA" },
                } },
            },
        },
        [260] = {
            ["Icy Veins"] = {
                ["PvP"] = { variantOrder = { "Best Midnight PvP Talent Builds for Outlaw Rogue in Arena" }, variants = {
                    ["Best Midnight PvP Talent Builds for Outlaw Rogue in Arena"] = { talentImportString = "CQQAAAAAAAAAAAAAAAAAAAAAAAgZAGzwMbzMzYGjZbzMzMbTbzY2mBAAAAAMLLjZwMjZWMzMGAAAAzYGAGzihBGY2YhWYzMAzMYgB" },
                } },
                ["Raid"] = { variantOrder = { "Outlaw Single Target - Trickster" }, variants = {
                    ["Outlaw Single Target - Trickster"] = { talentImportString = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMmZmtZmZmZMmF4BmZbaZw2MAAAAAALLzMzwMzMziZmZbAAAAYmBAjZxwADMLsQLsxAMzgBG" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves (Best)" }, variants = {
                    ["Delves (Best)"] = { talentImportString = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMjZmtZmZMzMzsAmZbaZw2MAAAAAA2mZmhZmZmFzMz2AAAAwYAwYWMMkBmFWoF2YAmZwMYG" },
                } },
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMjZmtZmZMzMzsAmZbaZw2MAAAAAAbbzMzwMzMziZmZbAAAAYmBAjZxwQGYWYhWYjBYmBDMA" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "CQQAAAAAAAAAAAAAAAAAAAAAAAgx2MMzMmZmtZmZmZMmF4BmZbaZw2MAAAAAAbbzMzwMzMziZmZbAAAAYmBAjZxwQGYWYhWYjBYmBDMA" },
                } },
            },
        },
        [261] = {
            ["Icy Veins"] = {
                ["Mythic+"] = { variantOrder = { "Mythic+/AoE - Deathstalker", "Mythic+/AoE - Trickster" }, variants = {
                    ["Mythic+/AoE - Deathstalker"] = { talentImportString = "CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTMbLjxMDjZmZmZGGbzYGbbzMzMzMjBjZ2GAAAAGMmFzyADYBsMMBmFMDzMAzYA" },
                    ["Mythic+/AoE - Trickster"] = { talentImportString = "CUQA5HmDzx68KWyrW/8Y781L7Dgx2MAAAAAwsMGLTMbLjxMMjZmZmZGGbzYGbbzMzMzMjBjZ2GAAAAGMGwY2MMwAziWoFbYGwMDmxA" },
                } },
                ["PvP"] = { variantOrder = { "Best Midnight PvP Talent Builds for Subtlety Rogue in Arena" }, variants = {
                    ["Best Midnight PvP Talent Builds for Subtlety Rogue in Arena"] = { talentImportString = "CUQAAAAAAAAAAAAAAAAAAAAAAAgZ2mBAAAAAmtZmZZiZZbMmZMDMzMzsMzsNjZmllhBzMGwMGAAAAzwMAGzihBGY2YhWsxMDYmBzYA" },
                } },
                ["Raid"] = { variantOrder = { "Single-Target - Deathstalker" }, variants = {
                    ["Single-Target - Deathstalker"] = { talentImportString = "CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTMbbjxMDDzMzMzw8AbzYGbbzMzMzMjBjZ2GAAAAGMmFzyADYBsMMBmFMDzMAzYA" },
                } },
            },
            ["Wowhead"] = {
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTMbbjxMDjZmZmZGGbzYGbbzMzMzMjBjZ2GAAAAGMmFzyADYBsMMhMLYGmZAmxA" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "CUQAAAAAAAAAAAAAAAAAAAAAAAgx2MAAAAAwsMGLTMbbjxMDDzMzMzw8AbzYGbbzMzMzMjBjZ2GAAAAGMmFzyADYBsMMhMLYGmZAmxA" },
                } },
            },
        },
    },
    SHAMAN = {
        [262] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Elemental Delves - Farseer" }, variants = {
                    ["Elemental Delves - Farseer"] = { talentImportString = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMGjZZZZMmhBAAAAsYmNYADY2YCMLAwsNzMjZ2WmJMzYsYmZGzYxyMjZmxMzCAwAAzMGGGA" },
                } },
                ["Mythic+"] = { variantOrder = { "Elemental Mythic+ - Farseer" }, variants = {
                    ["Elemental Mythic+ - Farseer"] = { talentImportString = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMGjZZZZMmhBAAAAsYmNYADY2YCMLAwsNzMjx2iJMzsNWmZmZMjFLzMmZGzMLAADAMzYYYA" },
                } },
                ["PvP"] = { variantOrder = { "Current build" }, variants = {
                    ["Current build"] = { talentImportString = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMLbzMGjZZZhxMMDAAAAsYmNYADY2YCMLAglxYMz2ipFzMjZWMmZMzsNbmZZGMzsMAwMDAmZMMjPA" },
                } },
                ["Raid"] = { variantOrder = { "Elemental Single Target - Farseer" }, variants = {
                    ["Elemental Single Target - Farseer"] = { talentImportString = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMmZmZZZZMMjBAAAAsYmNYADY2YCMLAwsNzMjZ2WmJMzsxyMzMjZwyMWMzwMLDAYAgZGDDD" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves (Best)" }, variants = {
                    ["Delves (Best)"] = { talentImportString = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMLLzMmZmZbZZMmxMDAAAAsZmNYADY2YCZWAgZZmZGjtFTYmxYZmZmZmxiFjFMmZWAAGAYmxwwA" },
                } },
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMGjZZZZMmhBAAAAsYmNYADY2YCZWAgZZmZGjtFTbMzYsMzMzYYZWMWmZGzMLAAzAgZGDDD" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "CYQAAAAAAAAAAAAAAAAAAAAAAAAAAAzMbLzMmZmZZbZMMjBAAAAsYmNYADY2YCZWAgZZmZGjtFTYmZZsMzMzYYZWmxiZGmZZAADAMzYYYA" },
                } },
            },
        },
        [263] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Delves - Totemic" }, variants = {
                    ["Delves - Totemic"] = { talentImportString = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMjZmZmZmZmZmZGzAAAAAAAAAALwGMjFN2GAzA2AYWmxMGLLzAzMGLmZmZMWYGAADMGzMxMDAMGA" },
                } },
                ["Mythic+"] = { variantOrder = { "AoE / Mythic+ - Stormbringer" }, variants = {
                    ["AoE / Mythic+ - Stormbringer"] = { talentImportString = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAAsBYzMG2gFYGGawCAzyMmxYZxYjZmtxyMzMzYswMAAzwYmhRgZGMYMA" },
                } },
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Enhancement Shaman" }, variants = {
                    ["Midnight PvP Talent Builds for Enhancement Shaman"] = { talentImportString = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMDMzMzMzMMzMDAAAAAAAAwGgNzYYDWgZYoBLAMbDGzssMjlxMz2YxYmhZ2GzAAMDzMzYmJwMDGMGA" },
                } },
                ["Raid"] = { variantOrder = { "Raid / Single Target - Stormbringer" }, variants = {
                    ["Raid / Single Target - Stormbringer"] = { talentImportString = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAA2AsZGDbwCMDDNYBgZZGzMjllZgZmNWmZmZYYMDAwMMmZMzEYmBDGDA" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves (Best)" }, variants = {
                    ["Delves (Best)"] = { talentImportString = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMjZmZmZmZmZmZGzAAAAAAAAAgFYDmxiGbDgZC2AYWmxMGLLzAzMGLmZmZMWYGAAgxYmJmZAGMGA" },
                } },
                ["Mythic+"] = { variantOrder = { "Mythic+/ AoE (Best)" }, variants = {
                    ["Mythic+/ AoE (Best)"] = { talentImportString = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAA2AsZGDbkFYGGawCAzyMmxYZxYjZmtxyMzMzgFmBAYGGzMMTgZGMYMA" },
                } },
                ["Raid"] = { variantOrder = { "Raid Cleave (Best)", "Single Target (Best)" }, variants = {
                    ["Raid Cleave (Best)"] = { talentImportString = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAA2AsZGDbkFYGGawCAzyMmZGLLzAzMbsMzMzwwYGAgZYMzYmJwMDGMGA" },
                    ["Single Target (Best)"] = { talentImportString = "CcQAAAAAAAAAAAAAAAAAAAAAAMzMzgZmZmZmhZmZAAAAAAAAA2AsZGDLkFYGGawCAzyMmZGLLzAzMbsMzMzwwYGAgZYMzYmJwMDGMGA" },
                } },
            },
        },
        [264] = {
            ["Icy Veins"] = {
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Restoration Shaman" }, variants = {
                    ["Midnight PvP Talent Builds for Restoration Shaman"] = { talentImportString = "CgQAAAAAAAAAAAAAAAAAAAAAAAAAAgBAAAAzMmltlxMzMzMzMzMjhFYDmxiGbDgZgN8AzgZbMGNLLzMLjZgFjZGzMbzmBAAAmZwMDAjBD" },
                } },
            },
        },
    },
    WARLOCK = {
        [265] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Affliction Delves - Soul Harvester" }, variants = {
                    ["Affliction Delves - Soul Harvester"] = { talentImportString = "CkQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxyMzYWGAAwMzsMLzMzyYAgxyyADYAzwWghtBAAgZAAAMzMmZY2GjZwMzMMMzMzAAmBG" },
                } },
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Affliction Warlock in Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Affliction Warlock in Arena"] = { talentImportString = "CkQAAAAAAAAAAAAAAAAAAAAAAsMGmZ0sNzYhZmZZAAAmZWmNzMLmBAGLLDMgBMDbBG2GAAAmBAAwMzMzMzMmZGmxMzMGMjZAAGwA" },
                } },
                ["Raid"] = { variantOrder = { "Affliction Single-Target - Soul Harvester" }, variants = {
                    ["Affliction Single-Target - Soul Harvester"] = { talentImportString = "CkQAAAAAAAAAAAAAAAAAAAAAAwMzMzoZhhZmZmlBAAYmZZ2mZmlxAAjllBGwEMDbBG2GAAAmBAAwMDzMjBzwMzMzMGMzMzAAmBG" },
                } },
            },
            ["Wowhead"] = {
                ["Mythic+"] = { variantOrder = { "Mythic+ (Best)" }, variants = {
                    ["Mythic+ (Best)"] = { talentImportString = "CkQAAAAAAAAAAAAAAAAAAAAAAwMMzoZzMz2MzYWGAAwMmlZZmZWGDAM22GYATwMsFYYbAAAYAAAYmZMjZmNGmZmZmhZYmZGAgZgB" },
                } },
                ["Raid"] = { variantOrder = { "Raid (Best)", "Raid Cleave (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "CkQAAAAAAAAAAAAAAAAAAAAAAwMzMzoZhhZmZmlBAAYmZZ2mZmlxAAjllBGwEMDbBG2GAAAmBAAwMDzMjBzwMzMzMGMzMzAAmBG" },
                    ["Raid Cleave (Best)"] = { talentImportString = "CkQAAAAAAAAAAAAAAAAAAAAAAwMmZGNbM2mZGzyAAAmZmlZxMzyYAgx2yADYCmhtADbDAAAzAAAYmZMjZmtxwYmZmZYYmZGAgZgB" },
                } },
            },
        },
        [266] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Demonology Delves - Soul Harvester" }, variants = {
                    ["Demonology Delves - Soul Harvester"] = { talentImportString = "CoQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxiZGzyAAAAAAAMWWGYADYG2CM2MmZsMmxMzMAwMzMGDwMzYmxMbAAgxMzMzYw2MDwA" },
                } },
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Demonology Warlock in Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Demonology Warlock in Arena"] = { talentImportString = "CoQAAAAAAAAAAAAAAAAAAAAAAsMGmZ0sNzYhZmZZAAAAAAAAAAAAAGjx2sMzMDDAYmZmZGAMzMzMDAAwYGzYMDLzAYA" },
                } },
                ["Raid"] = { variantOrder = { "Demonology Single-Target - Soul Harvester" }, variants = {
                    ["Demonology Single-Target - Soul Harvester"] = { talentImportString = "CoQAAAAAAAAAAAAAAAAAAAAAAwMzMzoZjhZmxsMAAAAAAAjtlBGwAmhtQGbmhZ2mlZmZMDAYMzMzAMzMmxMDAAwMzMzMjZYZAYA" },
                } },
            },
            ["Wowhead"] = {
                ["Raid"] = { variantOrder = { "Raid (Best)", "Raid Cleave (Best)" }, variants = {
                    ["Raid (Best)"] = { talentImportString = "CoQAAAAAAAAAAAAAAAAAAAAAAYmZMzoZjhZmxsMAAAAAAAgxMGWgB2GtQDLGjxysMzMjZAgZGzMzMzAMzMmZAAAGzMzMDDLzYAD" },
                    ["Raid Cleave (Best)"] = { talentImportString = "CoQAAAAAAAAAAAAAAAAAAAAAAYmhZGNbmx2MzYWGAAAAAAAwYGDLwAbj2ohFjZGLz2MzMmBAmZMmZmZAmZGmZDAAMmZmxwwyMGwA" },
                } },
            },
        },
        [267] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Destruction Delves - Hellcaller" }, variants = {
                    ["Destruction Delves - Hellcaller"] = { talentImportString = "CsQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxmZGzysZGzsYYZZmBAAzMjZmZxCMwsY0YGAzG2YAAgxMAAAzMYMzMmNAAAzMzMAAMDD" },
                } },
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Destruction Warlock in Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Destruction Warlock in Arena"] = { talentImportString = "CsQAAAAAAAAAAAAAAAAAAAAAAsMmxMjmtZGLMzMLDmxsMjZbxMAAYGjZmZxCMwsY0YGAzG2YAAgxAjNAgZGMzMzYAAAYGzAAwMDD" },
                } },
                ["Raid"] = { variantOrder = { "Destruction Single-Target - Hellcaller" }, variants = {
                    ["Destruction Single-Target - Hellcaller"] = { talentImportString = "CsQAAAAAAAAAAAAAAAAAAAAAAwMmZGNLMzmZmZWmFzMzsYMWMDAAmZGzMziNYgZxoxMAmtYjBAAGDM2AAmZwYGzYDAAwMzMAAMGG" },
                } },
            },
            ["Wowhead"] = {
                ["Mythic+"] = { variantOrder = { "Mythic+/ AoE (Best)" }, variants = {
                    ["Mythic+/ AoE (Best)"] = { talentImportString = "CsQAAAAAAAAAAAAAAAAAAAAAAwMjZGNbmZ2mZGzysZmZmFzMLLzDMAAYGjZmZBMmxwCZgthFaswAAAjZYAAmZAGzYMbAAAmZmBAAGG" },
                } },
                ["Raid"] = { variantOrder = { "Raid Cleave (Best)", "Raid Council (Best)", "Single Target (Best)" }, variants = {
                    ["Raid Cleave (Best)"] = { talentImportString = "CsQAAAAAAAAAAAAAAAAAAAAAAwMmZGNLMzmZmZWmlZmZmFjZbxDMAAYGjZmZxGMwsY0YGAzWsxAAAjBGbAAzMYMjZsBAAYmZGAAGDD" },
                    ["Raid Council (Best)"] = { talentImportString = "CsQAAAAAAAAAAAAAAAAAAAAAAwMjZGNLmxiZGzysNzMjFzYZZmBAAzgZmZxCMwsY0YGAzWsxAAAjZYAAwMDGzMmZDAAwMzMDAAzwA" },
                    ["Single Target (Best)"] = { talentImportString = "CsQAAAAAAAAAAAAAAAAAAAAAAwMmZGNLMzmZmZWmFzMzsYMWMDAAmZGzMziNYgZxoxMAmtYjBAAGDM2AAmZwYGzYDAAwMzMAAMGG" },
                } },
            },
        },
    },
    WARRIOR = {
        [71] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Arms Dungeons & Delves - Slayer" }, variants = {
                    ["Arms Dungeons & Delves - Slayer"] = { talentImportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphxYmZzMzMzYmxMDAAAAgxyMDMhxy2ALgBMDTgZwGYmhhBzyMbDwMDAmhBA" },
                } },
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Arms Warrior in Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Arms Warrior in Arena"] = { talentImportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphZGGLMzMzYGzMDAAAAgxyMDMhxy2AbgBMDTgZwGwMWMLzglZ2GgZGAmZYA" },
                } },
                ["Raid"] = { variantOrder = { "Arms Single-Target - Slayer" }, variants = {
                    ["Arms Single-Target - Slayer"] = { talentImportString = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzMmZGAAAghphxYmZzMzMzgxMDAAAAgZWmZAhxyyALgBMDTgZwGYmx2YbglZWGgZGAMDDA" },
                } },
            },
            ["Wowhead"] = {
                ["Delve"] = { variantOrder = { "Delves/ Open World (Best)" }, variants = {
                    ["Delves/ Open World (Best)"] = { talentImportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmxsMzMzYGAAAghphxYmZzMzMzYmxMDAAAAgxmZgJLAbmxwCMwMajGDWAzMMMGzmZbwMDAwMMA" },
                } },
                ["Mythic+"] = { variantOrder = { "Mythic+ Dungeons (Best)" }, variants = {
                    ["Mythic+ Dungeons (Best)"] = { talentImportString = "CcEAAAAAAAAAAAAAAAAAAAAAAgZmZmFzYmZGAAAghphxYmZzMzMzYmxMDAAAAgxyMDMhxy2AbgBMDTIzgNwMDDDmlZ2GgZGAMDDA" },
                } },
                ["Raid"] = { variantOrder = { "Raid Multitarget (Best)", "Single Target (Best)" }, variants = {
                    ["Raid Multitarget (Best)"] = { talentImportString = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzYmZGAAAghphxYmxyMzMzgxMDAAAAgZWmZgJMW2GYBMgZYCZGsBmZsN2GYZmtBYmBAzwA" },
                    ["Single Target (Best)"] = { talentImportString = "CcEAAAAAAAAAAAAAAAAAAAAAAAzMzsMzMmZGAAAghphxYmxyMzMzgxMDAAAAgZWmZAhxyyALgBMDTIzgNwMjtx2ALzsMAzMAYGGA" },
                } },
            },
        },
        [72] = {
            ["Icy Veins"] = {
                ["Delve"] = { variantOrder = { "Fury Dungeons & Delves - Thane" }, variants = {
                    ["Fury Dungeons & Delves - Thane"] = { talentImportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjZMz2yMzMjZmxMzMzMjZWmZmZmxsZmZGAAIMwGssY0YGQmFMjFAzgBAMzAwwiZAGD" },
                } },
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Fury Warrior in Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Fury Warrior in Arena"] = { talentImportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDzMjZWYmZGjxMzMzYmZmlhxMzMLmZmBAACDsBLLGNmBwshZsAYmFjFAYmBgxYYMDjB" },
                } },
                ["Raid"] = { variantOrder = { "Fury Single-Target - Slayer" }, variants = {
                    ["Fury Single-Target - Slayer"] = { talentImportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDzMmZ2MzMzMDjZmZGzYmlZmxMzMbmZmBAAixy2ALgJYGmAzwGwMDjNAAYmhxYYMYM" },
                } },
            },
            ["Wowhead"] = {
                ["Mythic+"] = { variantOrder = { "Mythic+ Dungeons (Best)" }, variants = {
                    ["Mythic+ Dungeons (Best)"] = { talentImportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjZMz2yMzMjZmxMzMzMjZWmZmZmxsYmZGAAIMwGssY0YGQmFMjFAzgBAMzAwwiZAGD" },
                } },
                ["Raid"] = { variantOrder = { "Raid Multitarget (Best)", "Single Target (Best)" }, variants = {
                    ["Raid Multitarget (Best)"] = { talentImportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDjxMzmZmZmZYMzMzMzYmlZMmZMbmZmBAAixy2ALgJYGmAzwGwMzmxGAAMzwYWGGDGD" },
                    ["Single Target (Best)"] = { talentImportString = "CgEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgGDzMmZ2MzMzMDjZmZGzMzsMzMmZmZzYmBAAixy2ALgJYGmAzwGwMDjNAAYmhxYYMYM" },
                } },
            },
        },
        [73] = {
            ["Icy Veins"] = {
                ["PvP"] = { variantOrder = { "Midnight PvP Talent Builds for Protection Warrior in Arena" }, variants = {
                    ["Midnight PvP Talent Builds for Protection Warrior in Arena"] = { talentImportString = "CkEAAAAAAAAAAAAAAAAAAAAAA02AAAzMzYmZGzY2MGDjxMNzMGLMzMDzYmZAAAAwyYAmxAMwGssY0YGAzGmZjxMjZwsAAzMAAMgxA" },
                } },
            },
        },
    },
}

TalentDex:SetBuildData(TalentDex.generatedBuildData)
