/**
 * Text scraped from web pages is presentation text, not a Lua literal. Keep it
 * on one line before it reaches the serializer so a page heading can never
 * terminate a generated Lua string by accident.
 */
export function normalizeLuaText(value) {
  return String(value ?? "")
    .replace(/\r\n|\r|\n/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Escapes a value for use between Lua double quotes. Lua decimal escapes use
 * three digits so a following digit in the source cannot become part of the
 * escape sequence.
 */
export function escapeLuaString(value, { normalize = true } = {}) {
  const text = normalize ? normalizeLuaText(value) : String(value ?? "");
  return text
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/[\x00-\x1F\x7F]/g, (character) => `\\${character.charCodeAt(0).toString().padStart(3, "0")}`);
}

function groupedBuilds(builds) {
  const root = {};
  for (const build of [...builds].sort((a, b) =>
    [a.classFile, a.specId, a.source, a.content, a.variant || "", a.talentImportString].join("\0")
      .localeCompare([b.classFile, b.specId, b.source, b.content, b.variant || "", b.talentImportString].join("\0")))) {
    const spec = (root[build.classFile] ??= {})[build.specId] ??= {};
    const source = (spec[build.source] ??= {});
    const content = (source[build.content] ??= []);
    content.push(build);
  }
  return root;
}

function renderContent(builds, indent) {
  if (builds.length === 1 && !builds[0].variant) {
    return `{ talentImportString = "${escapeLuaString(builds[0].talentImportString, { normalize: false })}" },`;
  }
  const variants = builds.map((build) => `\n${indent}    ["${escapeLuaString(build.variant || "Default")}"] = { talentImportString = "${escapeLuaString(build.talentImportString, { normalize: false })}" },`).join("");
  const order = builds.map((build) => `"${escapeLuaString(build.variant || "Default")}"`).join(", ");
  return `{ variantOrder = { ${order} }, variants = {${variants}\n${indent}} },`;
}

function groupedStatPriorities(priorities) {
  const root = {};
  for (const priority of [...priorities].sort((a, b) =>
    [a.classFile, a.specId, a.label, a.stats.join("\0")].join("\0")
      .localeCompare([b.classFile, b.specId, b.label, b.stats.join("\0")].join("\0")))) {
    const spec = (root[priority.classFile] ??= {})[priority.specId] ??= [];
    spec.push(priority);
  }
  return root;
}

function renderStatPriorities(priorities) {
  const root = groupedStatPriorities(priorities);
  const lines = ["TalentMinder.generatedStatPriorityData = {"];
  for (const [classFile, specs] of Object.entries(root).sort()) {
    lines.push(`    ["${escapeLuaString(classFile)}"] = {`);
    for (const [specId, lists] of Object.entries(specs).sort(([a], [b]) => Number(a) - Number(b))) {
      const order = lists.map((list) => `"${escapeLuaString(list.label)}"`).join(", ");
      lines.push(`        [${specId}] = { source = "Wowhead", priorityOrder = { ${order} }, priorities = {`);
      for (const list of lists) {
        const stats = list.stats.map((stat) => `"${escapeLuaString(stat)}"`).join(", ");
        lines.push(`            ["${escapeLuaString(list.label)}"] = { ${stats} },`);
      }
      lines.push("        } },");
    }
    lines.push("    },");
  }
  lines.push("}");
  return lines.join("\n");
}

function stableContentHash(builds, statPriorities) {
  const content = {
    builds: [...builds].map(({ classFile, specId, source, content: category, variant, talentImportString }) =>
      [classFile, specId, source, category, variant || "", talentImportString])
      .sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b))),
    statPriorities: [...statPriorities].map(({ classFile, specId, label, stats }) => [classFile, specId, label, stats])
      .sort((a, b) => JSON.stringify(a).localeCompare(JSON.stringify(b))),
  };
  return createHash("sha256").update(JSON.stringify(content)).digest("hex");
}

export function renderLua(builds, statPriorities = []) {
  const root = groupedBuilds(builds);
  const contentHash = stableContentHash(builds, statPriorities);
  const lines = [
    "-- Generated by TalentMinder data pipeline. Do not edit this file by hand.",
    `-- Content hash: ${contentHash}`,
    "local _, TalentMinder = ...",
    "",
    "TalentMinder.generatedBuildData = {",
  ];
  for (const [classFile, specs] of Object.entries(root).sort()) {
    lines.push(`    ["${escapeLuaString(classFile)}"] = {`);
    for (const [specId, sources] of Object.entries(specs).sort(([a], [b]) => Number(a) - Number(b))) {
      lines.push(`        [${specId}] = {`);
      for (const [sourceName, contents] of Object.entries(sources).sort()) {
        lines.push(`            ["${escapeLuaString(sourceName)}"] = {`);
        for (const [contentName, contentBuilds] of Object.entries(contents).sort()) {
          lines.push(`                ["${escapeLuaString(contentName)}"] = ${renderContent(contentBuilds, "                ")}`);
        }
        lines.push("            },");
      }
      lines.push("        },");
    }
    lines.push("    },");
  }
  lines.push(
    "}",
    "",
    renderStatPriorities(statPriorities),
    "",
    `TalentMinder.generatedDatasetMetadata = { schemaVersion = 1, contentHash = "${contentHash}" }`,
    "",
    "TalentMinder:SetBuildData(TalentMinder.generatedBuildData)",
    "TalentMinder:SetStatPriorityData(TalentMinder.generatedStatPriorityData)",
    "",
  );
  return lines.join("\n");
}
import { createHash } from "node:crypto";
